authors__ = [
"Seneca the Younger", 
"Albert Einstein", 
"Epictetus", 
"Michel de Montaigne", 
"Richard Feynman", 
"Gautama Buddha", 
"Samuel Johnson", 
"Winston Churchill", 
"Friedrich Nietzsche", 
"Abraham Lincoln",
"Paul Dirac",
"Niels Bohr",
"John von Neumann",
"Edward Teller",
"Jean-Paul Sartre",
"Eleanor Roosevelt",
"Sam Harris",
"Daniel Dennett",
"Christopher Hitchens",
"Richard Dawkins"
]

# the boolean is whether they might need translation
authors = [
("Seneca the Younger", True), 
("Albert Einstein", True), 
("Epictetus", True),
("Michel de Montaigne", True),
("Richard Feynman", False), 
("Gautama Buddha", False),
("Samuel Johnson", False),
("Winston Churchill", False),
("Friedrich Nietzsche", True),
("Albert Camus", True),
("David Deutsch", False),
("David Hume", False),
("Immanual Kant", True),
("Karl Popper", False),
("Abraham Lincoln", False),
("Paul Dirac", True),
("Niels Bohr", True),
("John von Neumann", True),
("Edward Teller", False),
("Jean-Paul Sartre", True),
("Eleanor Roosevelt", False),
("Sam Harris", False),
("Daniel Dennett", False),
("Christopher Hitchens", False),
("Richard Dawkins", False),
#("Socrates", True), some problem with Socrates bio
("Plato", True),
("Franklin D. Roosevelt", False),
("Adam Smith", False),
("Lee Smolin", False),
("Charles Darwin", False),
("Henry David Thoreau", False),
("David Hume", False),
("Charles Dickens", False),
("Emily Dickinson", False),
("Philip Larkin", False),
("Max Tegmark", False),
("Edward Witten", False),
("Roger Penrose", False),
("Geoffrey Hinton", False),
("Raymond Kurzweil", False),
("Stuart Russell", False),
("Yann LeCun", False),
("Steven Pinker", False),
("Erwin Schrödinger", False),
("Nick Bostrom", False),
("William James", False),
("William Shakespeare", False),
("Ada Lovelace", False)
]
